### ISSUE TITLE
音乐播放器

### ISSUE THREAD

**Issue by atangccc** [wenjing-xin/plugin-blog-hao#1]
其实可以通过blogHao集成类似于网易云提供的外链播放器，样式可以参考下图
![1720673967409](https://github.com/wenjing-xin/plugin-blog-hao/assets/111550294/7045f54a-7662-4e5e-8ba7-c07c7e7cc783)
![0c4230f63aff31485a1144f5a5a0052](https://github.com/wenjing-xin/plugin-blog-hao/assets/111550294/17825085-7d6f-45cd-8ce0-909719fca1b0)

**Comment by wenjing-xin** [comment]
这个功能我最后想了下，因为已经有开发者开发专门的音乐插件，所以我在开发其实多此一举了，等待其他开发者后续上架音乐插件吧
