### ISSUE TITLE
幻灯片功能与主题字体冲突

### ISSUE THREAD

**Issue by Terryisthebest** [wenjing-xin/plugin-blog-hao#2]
禁用幻灯片功能后：
![截屏2024-07-16 下午10 11 08](https://github.com/user-attachments/assets/d5374b0c-4b97-44d0-af24-3b9a57cda125)
启用幻灯片功能后：
![截屏2024-07-16 下午10 12 02](https://github.com/user-attachments/assets/5f7dbf87-3da1-4e0a-ae19-f0671db9081d)
首页和文章标题的字体均无法正常显示

我的halo 版本 2.17.0 
主题为Sakura 2.4.0

**Comment by wenjing-xin** [comment]
我测试了下，主要是因为 幻灯片功能的部分 css 会重设一些元素样式，比如字体大小，所以会导致出现这种情况，下个版本我会修复！

**Comment by Terryisthebest** [comment]
okok 感谢啦！！
