### ISSUE TITLE
文章文字前进两个空格

### ISSUE THREAD

**Issue by OORTaka0825** [wenjing-xin/plugin-blog-hao#3]
plugin-blog-hao插件用在Holo Hao主题那个文章前进两个空格会使图片移动出文章列表外
![HX8Mb3rhZI](https://github.com/user-attachments/assets/8d312bad-ef43-4840-9ecb-6624f47d7ff3)

**Comment by wenjing-xin** [comment]
可以提供下出问题的站点地址吗

**Comment by OORTaka0825** [comment]
> 可以提供下出问题的站点地址吗

https://oortaka.top/archives/wei-ming-ming-wen-zhang

**Comment by wenjing-xin** [comment]
新版本已经修复，等待新版本上架后更新就可以了
