### ISSUE TITLE
更新最新版本之后访问主页报500

### ISSUE THREAD

**Issue by MoTingFeng** [wenjing-xin/plugin-blog-hao#4]
管理界面能进,主页及其他的访问报500
halo版本:2.17.2
OpenResty版本:1.21.4.3-3-3-focal
下面是halo的日志
[_opt_1panel_apps_halo_halo_docker-compose.yml-20240729164048.log](https://github.com/user-attachments/files/16409947/_opt_1panel_apps_halo_halo_docker-compose.yml-20240729164048.log)

**Comment by wenjing-xin** [comment]
已修复，主要是没有对配置判空，但是我已经在配置文件上做了默认值，不知道为什么在生产环境没起作用！

**Comment by XJY00** [comment]
问题依旧存在：
1.1.0版本 更新未修复？
与第三方主题不兼容？

**Comment by wenjing-xin** [comment]
等下个小版本吧，V1.1.0的更新日志看一看，这个版本实在呢提issue之前发布的

**Comment by yoyo-ouo** [comment]
+1
关掉插件之后访问就正常了

**Comment by wodepig** [comment]
2.19.1版本启用后会导致主页打不开
等更新...

**Comment by sucooer** [comment]
500错误

**Comment by wenjing-xin** [comment]
已修复，请使用 V1.1.1版本
