### ISSUE TITLE
插件的幻灯片功能与样式好像和主题自带的冲突,导致自带轮播图不能轮播

### ISSUE THREAD

**Issue by XJ814** [wenjing-xin/plugin-blog-hao#5]
![微信图片_20240801115608](https://github.com/user-attachments/assets/20c53e1d-b884-4eac-acba-cb9ab5177724)
![微信图片_20240801115613](https://github.com/user-attachments/assets/b53adcc3-62bd-4333-853f-7346e0b9478a)
样式也被改变了,自带的轮播图无法轮播,企业主题,大佬能解决一下吗

**Comment by wenjing-xin** [comment]
有站点地址吗？我看看 可能是都适用了 swiperjs 这个前端库，类名冲突导致的

**Comment by XJ814** [comment]
zhikd.com
